---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-app
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld-app
        image: 956336999236.dkr.ecr.us-east-2.amazonaws.com/flask-helloworld:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  namespace: apps
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 80          # External port (what you access)
      targetPort: 5000  # Container port
  type: ClusterIP       # Use LoadBalancer if you want an AWS NLB/ELB for external access